<?php

namespace ReplyVP\Entities;

class Message {
    private int $id;
    private int $ticket_id;
    private int $user_id;
    private string $message;
    private \DateTime $created_at;

    public function __construct(
        int $id,
        int $ticket_id,
        int $user_id,
        string $message,
        \DateTime $created_at;
    ) {
        $this->id = $id;
        $this->ticket_id = $ticket_id;
        $this->user_id = $user_id;
        $this->message = $message;
        $this->created_at = $created_at;
    }

    public function getId(): string {
        return $this->id;
    }

    public function getTicketId(): string {
        return $this->ticket_id;
    }

    public function getUserId(): string {
        return $this->user_id;
    }

    public function getMessage(): string {
        return $this->message;
    }
    
    public function getCreatedAt(): string {
        return $this->created_at;
    }

    // message Id is generated by the database

    public function setTicketId(int $ticketId) {
        $this->ticketId = $ticketId;
    }

    public function setMessage(string $message): void {
        $this->message = $message;
    }
}