<?php

namespace ReplyVP\Entities;

class Ticket {
    private int $id;
    private string $subject;
    private bool $status;
    private bool $isRepeat;
    private \DateTime $createdAt;
    private int $userId;

    public function __construct(
        int $id,
        string $subject,
        bool $status,
        bool $isRepeat,
        \DateTime $createdAt,
        int $userId = 0,
    ) {
        $this->id = $id;
        $this->subject = $subject;
        $this->status = $status;
        $this->isRepeat = $isRepeat;
        $this->createdAt = $createdAt;
        $this->userId = $userId;
    }

    public function getId(): int {
        return $this->id;
    }

    public function getSubject(): string {
        return $this->subject;
    }


    public function getStatus(): bool {
        return $this->status;
    }

    public function isRepeat(): bool {
        return $this->isRepeat;
    }

    public function getCreatedAt(): \DateTime {
        return $this->createdAt;
    }

    public function getUserId(): int {
        return $this->userId;
    }

    // ticket id is generated by the database

    public function setSubject(string $subject): void {
        $this->subject = $subject;
    }
    
    public function setUserId(int $userid) {
        $this->userId = $userId;
    }
}