services:
  db:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: unless-stopped

  web:
    build: ./web
    container_name: php-container
    restart: always
    volumes:
      - ./web/api:/var/www/html/api
      - ./web/auth:/var/www/html/auth
    ports:
      - "8080:80"
    depends_on:
      - db