  services:

    db:
      image: postgres:14
      container_name: postgresweb_db
      environment:
        POSTGRES_DB: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      volumes:
        - type: volume
          source: postgres_data
          target: /var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d test"]
        interval: 5s
        timeout: 5s
        retries: 5

    web:
      image: stllorg/reply-core
      restart: unless-stopped
      environment:
        - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/test
        - QUARKUS_DATASOURCE_USERNAME=postgres
        - QUARKUS_DATASOURCE_PASSWORD=postgres
        - MP_JWT_VERIFY_PUBLICKEY_LOCATION=/run/secrets/public_key_secret
        - SMALLRYE_JWT_SIGN_KEY_LOCATION=/run/secrets/private_key_secret
      secrets:
        - public_key_secret
        - private_key_secret
      depends_on:
        - db
    
    nginx:
      build:
        context: ./nginx
        dockerfile: Dockerfile
      container_name: nginx_proxy
      ports:
        - "80:80"
      volumes:
        - ./frontend:/usr/share/nginx/html
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - web
      secrets:
        - public_key_secret

  secrets:
    public_key_secret:
      file: ./keys/jwt/publicKey.pem
    private_key_secret:
      file: ./keys/jwt/privateKey.pem

  volumes:
    postgres_data: